# author is used in the atom feed
title: JBoss Developer Framework
author: JBoss Developer Framework
jira_key: JDF
ohloh_id: jboss-jdf
disqus: jdf
website_source_repo: https://github.com/jboss-jdf/jdf-site
irc_transcripts: http://transcripts.jboss.org/channel/irc.freenode.org/%23jboss-jdf/
version: 1.0.6.Final
profiles:
  development:
    base_url: http://localhost:4242
    minify: false
    google_plusone: false
  sandbox:
    base_url: http://site-jdf.rhcloud.com
    minify: false
    google_plusone: false
  production:
    base_url: http://jboss.org/jdf
    minify: true
    google_plusone: true
  staging:
    base_url: http://jboss.org/jdf/stage
    minify: true
    google_plusone: false
