# author is used in the atom feed
title: JBoss Develoepr Framework
author: JBoss Developer Framework
jira_key: JDF
ohloh_id: jbossdeveloperframework
disqus: jdf
show_debug: true
website_source_repo: https://github.com/pmuir/jdf-site


profiles:
  development:
    base_url: http://people.redhat.com/~pmuir/jdfsite
    deploy:
      host: people.redhat.com 
      path: /home/remote/pmuir/public_html/jdfsite 
