# author is used in the atom feed
title: JBoss Developer Framework
author: JBoss Developer Framework
jira_key: JDF
ohloh_id: jbossdeveloperframework
disqus: jdf
website_source_repo: https://github.com/pmuir/jdf-site

profiles:
  debug:
    show_debug: true
    base_url: http://localhost:4242
  staging:
    base_url: http://site-jdf.rhcloud.com
